#define CANCEL "Cancel"
#define DONE "Done"
#define SELECT_CHAPTER "Select Chapter"
#define NOTE_DELETED "Note Deleted!"
#define CLOSE "Close"
#define GET_VERSE "Get Verse"
#define DELETE_NOTE "Delete Note"
#define NO "No"
#define YES "Yes"
#define OK "OK"
#define GO_TO "Go to"
#define GO "Go"
#define SAVE "Save"
#define DELETE "Delete"
#define EDIT "Edit"
#define REMOVED "Removed"
#define REMOVE "Remove"
#define BOOKMARK "Bookmark"
#define BOOKMARKED "Bookmarked"
#define BOOKMARK_REMOVED "Bookmark Removed!"
#define SEARCH "Search"
#define DAY_MODE "Day Mode Reading"
#define NIGHT_MODE "Night Mode Reading"
#define VERSE_VIEW "Verse View"
#define FONT_SIZE "Font Size"
#define BOOKMARKS "Bookmarks"
#define NOTES "Notes"
#define SHARE "Share"
#define COPY "Copy"
#define ABOUT "About"
#define HELP "Help"
#define SEARCH_KEYWORD_IS_TOO_LARGE "Search keyword is too large"
#define SEARCH_KEYWORD_IS_TOO_SMALL "Search keyword is too small"
#define LOADING_BOOKS "Loading Books..."
#define SELECT_BOOK "Select Book"
#define SEARCH_PREFERENCES "Search Preferences"
#define ENTIRE_BIBLE "Entire Bible"
#define NEW_TESTAMENT "New Testament"
#define OLD_TESTAMENT "Old Testament"
#define CUSTOM_SEARCH "Custom Search"
#define FROM "From"
#define TO "To"
#define WHOLE_WORD "Whole word"
#define STRICT_SEARCH "Strict search"
#define ENTER_THE_KEYWORD "Enter the keyword"
#define NO_VERSE_SELECTED "No verse selected"
#define NOT_ENOUGH_MEMORY "Not enough memory to do the operation!"
#define VERSE_ALREADY_BOOKMARKED "Verse already bookmarked!"
#define NOTHING_TO_SAVE "Nothing to save!"
#define NOTE_IS_TOO_LARGE "Note is too large :("
#define NOTE_SAVED "Note saved"
#define ENTER_THE_NOTES "Enter the notes"
#define SELECT_ALL "Select All"
#define BOOKMARK_VERSE "Bookmark Verse"
#define REMOVE_BOOKMARK "Remove bookmark"
#define ADD_NOTES "Add notes"
#define VIEW_NOTES "View notes"
#define SHARE_VERSE "Share Verse"
#define COPY_VERSE "Copy Verse"
#define COPYRIGHT "Copyright © 2015 Godly T Alias"
#define VERSION "GTA v0.5"
#define TITLE "HOLY BIBLE"
#define LOADING_DATABASE "Loading Database..."
#define RATE_APP "Rate Application"
#define BUGS_SUGGESTIONS "Bugs / Suggestions"
#define SET_DEFAULT "Set Default"
#define PARALLEL_READING "Parallel Reading"
#define GO_TO_STORE "Go to Store"
#define ON "On"
#define OFF "Off"
#define GTA_APP_INSTALL_WARNING "No other GTA Bible applications above v0.5 is detected. Please install / update application from Tizen Store"
#define PARALLEL_READING_FAILED "Parallel reading failed!. Please re-install the required application."
#define PRESS_BACK_AGAIN_TO_EXIT "Press back again to exit!"
