#define CANCEL "റദ്ദാക്കുക"
#define DONE "ചെയ്തു"
#define SELECT_CHAPTER "അദ്ധ്യായം തിരഞ്ഞെടുക്കുക"
#define NOTE_DELETED "കുറിപ്പ് ഡിലീറ്റ് ചെയ്തു!"
#define CLOSE "അടയ്ക്കുക"
#define GET_VERSE "വാക്യം കാണുക"
#define DELETE_NOTE "കുറിപ്പ് ഡിലീറ്റ് ചെയ്യണോ"
#define NO "വേണ്ട"
#define YES "വേണം"
#define OK "ശരി"
#define GO_TO "ലേക്ക് പോകുക"
#define GO "ശരി"
#define SAVE "സേവ്"
#define DELETE "ഡിലീറ്റ്"
#define EDIT "എഡിറ്റ്"
#define REMOVED "ഒഴിവാക്കി"
#define REMOVE "ഒഴിവാക്കണോ"
#define BOOKMARK "ബുക്ക്മാർക്ക്"
#define BOOKMARKED "ബുക്ക്മാർക്ക് ചെയ്തു"
#define BOOKMARK_REMOVED "ബുക്ക്മാർക്ക് ഒഴിവാക്കി!"
#define SEARCH "തിരയുക"
#define DAY_MODE "പകൽ മോഡ്"
#define NIGHT_MODE "രാത്രി മോഡ്"
#define FONT_SIZE "അക്ഷര വലിപ്പം"
#define BOOKMARKS "ബുക്ക്മാർക്കുകൾ"
#define NOTES "കുറിപ്പുകൾ"
#define SHARE "പങ്കിടുക"
#define COPY "പകർത്തുക"
#define ABOUT "വിവരണം"
#define HELP "സഹായം"
#define SEARCH_KEYWORD_IS_TOO_LARGE "വാക്ക് വളരെ വലുതാണ്"
#define SEARCH_KEYWORD_IS_TOO_SMALL "വാക്ക് വളരെ ചെറുതാണ്"
#define LOADING_BOOKS "ലോഡ് ചെയ്യുന്നു..."
#define SELECT_BOOK "പുസ്തകം തിരഞ്ഞെടുക്കുക"
#define SEARCH_PREFERENCES "തിരച്ചിൽ മുൻഗണനകൾ"
#define ENTIRE_BIBLE "മുഴുവൻ<br/>ബൈബിൾ"
#define NEW_TESTAMENT "പുതിയ<br/>നിയമം"
#define OLD_TESTAMENT "പഴയ<br/>നിയമം"
#define CUSTOM_SEARCH "സ്വതന്ത്ര<br/>തിരയൽ"
#define FROM "തുടക്കം"
#define TO "അവസാനം"
#define WHOLE_WORD "മുഴുവൻ<br/>വാക്ക്"
#define STRICT_SEARCH "കർശന<br/>തിരച്ചിൽ"
#define ENTER_THE_KEYWORD "വാക്ക് ടൈപ്പ് ചെയ്യുക"
#define NO_VERSE_SELECTED "വാക്യം തിരഞ്ഞെടുത്തിട്ടില്ല"
#define NOT_ENOUGH_MEMORY "ഓപ്പറേഷൻ ചെയ്യാൻ മതിയായ മെമ്മറി ഇല്ല!"
#define VERSE_ALREADY_BOOKMARKED "വാക്യം നേരത്തെ ബുക്ക്മാർക്ക് ചെയ്തതാണ്"
#define NOTHING_TO_SAVE "ഒന്നും സേവ് ചെയ്യാനില്ല!"
#define NOTE_IS_TOO_LARGE "കുറിപ്പ് വളരെ വലുതാണ് :("
#define NOTE_SAVED "കുറിപ്പ് സേവ് ചെയ്തു"
#define ENTER_THE_NOTES "കുറിപ്പ്  എഴുതുക"
#define SELECT_ALL "എല്ലാം തിരഞ്ഞെടുക്കുക"
#define BOOKMARK_VERSE "വാക്യം ബുക്ക്മാർക്ക് ചെയ്യുക"
#define REMOVE_BOOKMARK "ബുക്ക്മാർക്ക് ഒഴിവാക്കുക"
#define ADD_NOTES "കുറിപ്പ് ചേർക്കുക"
#define VIEW_NOTES "കുറിപ്പ് വായിക്കുക"
#define SHARE_VERSE "വാക്യം പങ്കിടുക"
#define COPY_VERSE "വാക്യം പകർത്തുക"
#define COPYRIGHT "Copyright © 2015 Godly T Alias"
#define VERSION "GTA v0.5"
#define TITLE "സത്യവേദപുസ്തകം"
#define LOADING_DATABASE "ഡാറ്റാബേസ് ലോഡ് ചെയ്യുന്നു..."
#define RATE_APP "വിലയിരുത്തുക"
#define BUGS_SUGGESTIONS "പിശക്  / നിർദ്ദേശങ്ങൾ"
#define SET_DEFAULT "സാധാരണ വലുപ്പം"
#define PARALLEL_READING "സമാന്തര വായന"
#define GO_TO_STORE "സ്റ്റോറിലേക്ക് പോകുക"
#define ON "ഓൺ"
#define OFF "ഓഫ്"
#define GTA_APP_INSTALL_WARNING "മറ്റു GTA ബൈബിൾ അപ്ലിക്കേഷനുകൾ കണ്ടെത്തിയില്ല. സ്റ്റോറിൽ നിന്നും അപ്ലിക്കേഷനുകൾ ഇൻസ്റ്റോൾ / അപ്ഡേറ്റ് ചെയ്യുക."
#define PARALLEL_READING_FAILED "പരാജയപ്പെട്ടു ! ആവശ്യമായ ആപ്ലിക്കേഷൻ ഇൻസ്റ്റാൾ ചെയ്യുക."
#define BIBLE_NAME_STRING "Malayalam Bible"
#define LANGUAGE_SUPPORT_STRING "This application requires Malayalam language support!"
#define PRESS_BACK_AGAIN_TO_EXIT "അടയ്ക്കുന്നതിന് വീണ്ടും ബാക്ക് അമർത്തുക"
