#define CANCEL "रद्द"
#define DONE "पूर्ण"
#define SELECT_CHAPTER "अध्याय चुनें"
#define NOTE_DELETED "नोट हटा दिया!"
#define CLOSE "बंद करें"
#define GET_VERSE "कविता दिखाइए"
#define DELETE_NOTE "नोट हटाऐँ"
#define NO "नहीं"
#define YES "हाँ"
#define OK "ठीक"
#define GO_TO "से जाओ"
#define SAVE "सहेजें"
#define DELETE "हटाऐँ"
#define EDIT "संपादित"
#define REMOVED "हटा दिया"
#define REMOVE "हटाऐँ"
#define BOOKMARK "बुकमार्क"
#define BOOKMARKED "बुकमार्क किया"
#define BOOKMARK_REMOVED "बुकमार्क हटा दिया!"
#define SEARCH "खोजें"
#define DAY_MODE "दिन मोड"
#define NIGHT_MODE "रात मोड"
#define FONT_SIZE "फ़ॉन्ट आकार"
#define BOOKMARKS "बुकमार्क"
#define NOTES "नोट्स"
#define SHARE "साझा करें"
#define COPY "कापी करें"
#define ABOUT "के बारे में"
#define HELP "मदद"
#define SEARCH_KEYWORD_IS_TOO_LARGE "कीवर्ड बहुत बड़ा है"
#define SEARCH_KEYWORD_IS_TOO_SMALL "कीवर्ड बहुत छोटा है"
#define LOADING_BOOKS "लोड हो रहा है..."
#define SELECT_BOOK "पुस्तक चुनें"
#define SEARCH_PREFERENCES "खोज प्राथमिकताएं"
#define ENTIRE_BIBLE "पूरे बाइबल"
#define NEW_TESTAMENT "नए करार"
#define OLD_TESTAMENT "पूर्व विधान"
#define CUSTOM_SEARCH "स्वतंत्र खोज"
#define FROM "से"
#define TO "तक"
#define WHOLE_WORD "पूरा शब्द"
#define STRICT_SEARCH "सख्त खोज"
#define ENTER_THE_KEYWORD "कीवर्ड दर्ज करें"
#define NO_VERSE_SELECTED "कविता चयन नहीं किया है"
#define NOT_ENOUGH_MEMORY "प्रक्रिया करने के लिए मेमोरी पर्याप्त नहीं!"
#define VERSE_ALREADY_BOOKMARKED "पहले बुकमार्क किया था!"
#define NOTHING_TO_SAVE "नोट बहुत छोटा है!"
#define NOTE_IS_TOO_LARGE "नोट बहुत बड़ी है :("
#define NOTE_SAVED "नोट संग्रहीत किया"
#define ENTER_THE_NOTES "नोट दर्ज करें"
#define SELECT_ALL "सभी चुनें"
#define BOOKMARK_VERSE "कविता बुकमार्क करें"
#define REMOVE_BOOKMARK "बुकमार्क हटाऐँ"
#define ADD_NOTES "नोट जोड़ें"
#define VIEW_NOTES "नोट देखें"
#define SHARE_VERSE "कविता साझा करें"
#define COPY_VERSE "कविता कापी करें"
#define COPYRIGHT "Copyright © 2015 Godly T Alias"
#define VERSION "GTA v0.5"
#define TITLE "पवित्र बाइबिल"
#define LOADING_DATABASE "डेटाबेस लोड हो रहा है..."
#define RATE_APP "रेट करें"
#define BUGS_SUGGESTIONS "बग / सुझाव"
#define SET_DEFAULT "डिफॉल्ट सेट करें"
#define PARALLEL_READING "समानांतर पढ़ना"
#define GO_TO_STORE "स्टोर में जाओ"
#define ON "सक्षम करें"
#define OFF "अक्षम करें"
#define GTA_APP_INSTALL_WARNING "किसी भी जीटीए बाइबिल एप्लिकेशन नहीं मिल सका।स्टोर से डाउनलोड करें ।"

